### ISSUE TITLE
Correct the "To Top" arrow

### ISSUE THREAD

**Issue by oynomak** [Auto-HubUTech/Auto-hub4tech#3]
Correct the **To Top** arrow to enable it so that it can also work on gray backgrounded sections!

**Comment by oynomak** [comment]
Hello @MuhimakaziClaudette , ndabona kariya ka Arrow ka "To Top" iyo kageze kuri background ya gris kadakora. Ni  ukureba uko wagahindurira ibara, kakajya gakora kuri buri background. Cg ukareba muri JQuery zako niba nta kundi twagakora. Nibyanga ni ugushaka akandi ugasimbuza.

_## Ubwo niba hari icyo nagufasha wambwira hakiri kare_. Kuko Website igomba kuba ikora kandi irangiye **ejo nimugoroba.**

**Comment by MuhimakaziClaudette** [comment]
narangije kugakora nagasimbuje akandi
